### ISSUE TITLE
Intent to deprecate

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/purescript-base#13]
We intend to deprecate this library as part of a purescript-contrib cleanup -- see [the full discussion on Discourse](https://discourse.purescript.org/t/proposed-purescript-contrib-library-deprecations) for more details on the effort.

We're considering deprecating purescript-base because it hasn't seen activity in years (including several compiler versions) and because in the age of package sets ([see Spago](https://github.com/purescript/spago)) this library is no longer needed.

"Deprecation" means that this library either moves to a private maintainer or is moved to the purescript-deprecated organization and made read-only. If the library is deprecated it can still be installed but it won't receive future updates.

Please feel free to weigh in on this discussion either here or in the [Discourse discussion](https://discourse.purescript.org/t/proposed-purescript-contrib-library-deprecations).

**Comment by thomashoneyman** [comment]
@jdegoes 👋 pinging you as the maintainer of the library just in case you weren’t notified via watching the repository. If anyone else ought to be explicitly looped in please feel free to mention them also! Thanks!

**Comment by jdegoes** [comment]
Looks good to me!
