### ISSUE TITLE
Add Base module?

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-base#2]
With module reexports, maybe it makes sense to have a `Base` module here which reexports things like `Data.Maybe`, `Data.Either`, etc.

Then `import Base` would give you a pretty useable system.

We'd have to be careful not to export too much, since we can't selectively reexport right now.

**Comment by jdegoes** [comment]
:+1:

**Comment by jonsterling** [comment]
Can this ticket be closed now that there is a `Base` module?

**Comment by paf31** [comment]
Yep, thanks.
