### ISSUE TITLE
Bump at least purescript-strings, purescript-enums

### ISSUE THREAD

**Issue by jonsterling** [purescript-contrib/purescript-base#6]
Doing this will alleviate a number of unfortunate explicit resolutions in various packages.

**Comment by jdegoes** [comment]
The stated purpose is to choose a mutually compatible set of dependencies, so bumping these two may lead to other bumps as necessary for compatibility (which is not a bad thing, just FYI).

**Comment by garyb** [comment]
I'd suggest bumping everything that isn't the latest revision, if possible. The downside is it may result in there being new things that need fixing, as `free` has changed, etc.

**Comment by jonsterling** [comment]
@jdegoes @garyb My plan is to try and get the newest possible mutually compatible set of dependencies... I think it's worth allowing this task to spiral out into whatever parts of the ecosystem are necessary, so that we can keep purescript packages up to date.

**Comment by jdegoes** [comment]
Agreed, it would also be simpler to maintain our vast ecosystem of libraries if they all depended just on base instead of manually coding each and every dependency.
